version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1080:1080"
    volumes:
      - ./src:/home/node/src
      - node_modules:/home/node/src/jyanken/node_modules
    tty: true

volumes:
  node_modules:
    driver: local
